// <auto-generated />
using System;
using ItAssetManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ItAssetManagement.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002151601_InitialM1")]
    partial class InitialM1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ItAssetManagement.Domain.Entities.Asset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("asset_code");

                    b.Property<long>("AssetTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("asset_type_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("IN_STOCK")
                        .HasColumnName("current_status");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("operating_system");

                    b.Property<long>("OwningDepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("owning_department_id");

                    b.Property<decimal?>("PurchaseCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("purchase_cost");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Specification")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("specification");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.Property<DateOnly?>("WarrantyEndDate")
                        .HasColumnType("date")
                        .HasColumnName("warranty_end_date");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_assets_created_by_user_id");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_assets_updated_by_user_id");

                    b.HasIndex("AssetTypeId", "CurrentStatus")
                        .HasDatabaseName("ix_assets_type_status");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("AssetTypeId", "CurrentStatus"), new[] { "AssetCode", "Name" });

                    b.HasIndex("IsArchived", "UpdatedAtUtc")
                        .HasDatabaseName("ix_assets_archived");

                    b.HasIndex("OwningDepartmentId", "CurrentStatus")
                        .HasDatabaseName("ix_assets_department_status");

                    b.ToTable("assets", "public", t =>
                        {
                            t.HasCheckConstraint("ck_assets_archive_time", "(NOT is_archived AND archived_at_utc IS NULL) OR (is_archived AND archived_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_assets_purchase_cost_nonnegative", "purchase_cost >= 0 AND purchase_cost <> 'NaN'::numeric");

                            t.HasCheckConstraint("ck_assets_row_version_length", "octet_length(row_version) = 16");

                            t.HasCheckConstraint("ck_assets_status", "current_status IN ('IN_STOCK','IN_USE','MAINTENANCE','BROKEN','RETIRED')");

                            t.HasCheckConstraint("ck_assets_warranty_date", "warranty_end_date >= purchase_date");
                        });
                });

            modelBuilder.Entity("ItAssetManagement.Domain.Entities.AssetStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetId")
                        .HasColumnType("bigint")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("ChangedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at_utc")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<long?>("ChangedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("changed_by_user_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("from_status");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_asset_status_histories");

                    b.HasIndex("ChangedByUserId")
                        .HasDatabaseName("ix_asset_status_histories_changed_by_user_id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_asset_status_histories_correlation");

                    b.HasIndex("AssetId", "ChangedAtUtc", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_asset_status_histories_asset_time");

                    b.ToTable("asset_status_histories", "public", t =>
                        {
                            t.HasCheckConstraint("ck_asset_status_histories_from_status", "from_status IN ('IN_STOCK','IN_USE','MAINTENANCE','BROKEN','RETIRED')");

                            t.HasCheckConstraint("ck_asset_status_histories_source", "source IN ('ASSIGNMENT','MAINTENANCE','ADMIN','IMPORT','SYSTEM')");

                            t.HasCheckConstraint("ck_asset_status_histories_status_changed", "from_status IS NULL OR from_status <> to_status");

                            t.HasCheckConstraint("ck_asset_status_histories_to_status", "to_status IN ('IN_STOCK','IN_USE','MAINTENANCE','BROKEN','RETIRED')");
                        });
                });

            modelBuilder.Entity("ItAssetManagement.Domain.Entities.AssetType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<int?>("DefaultUsefulLifeMonths")
                        .HasColumnType("integer")
                        .HasColumnName("default_useful_life_months");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_asset_types");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("ix_asset_types_active_name");

                    b.ToTable("asset_types", "public", t =>
                        {
                            t.HasCheckConstraint("ck_asset_types_row_version_length", "octet_length(row_version) = 16");

                            t.HasCheckConstraint("ck_asset_types_useful_life_positive", "default_useful_life_months > 0");
                        });
                });

            modelBuilder.Entity("ItAssetManagement.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("action");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("USER")
                        .HasColumnName("actor_type");

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<byte[]>("EntryHash")
                        .HasColumnType("bytea")
                        .HasColumnName("entry_hash");

                    b.Property<string>("FailureReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("failure_reason_code");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values_json");

                    b.Property<DateTime>("OccurredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values_json");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<byte[]>("PreviousEntryHash")
                        .HasColumnType("bytea")
                        .HasColumnName("previous_entry_hash");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("request_method");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("request_path");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_logs_correlation");

                    b.HasIndex("ActorUserId", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_logs_actor_time");

                    b.HasIndex("OccurredAtUtc", "Id")
                        .IsDescending()
                        .HasDatabaseName("ix_audit_logs_time");

                    b.HasIndex("Action", "Outcome", "OccurredAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_audit_logs_action_outcome");

                    b.HasIndex("EntityType", "EntityId", "OccurredAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_audit_logs_entity");

                    b.ToTable("audit_logs", "public", t =>
                        {
                            t.HasCheckConstraint("ck_audit_logs_actor_identity", "(actor_type = 'USER' AND actor_user_id IS NOT NULL) OR (actor_type IN ('SYSTEM','ANONYMOUS') AND actor_user_id IS NULL)");

                            t.HasCheckConstraint("ck_audit_logs_actor_type", "actor_type IN ('USER','SYSTEM','ANONYMOUS')");

                            t.HasCheckConstraint("ck_audit_logs_hash_length", "entry_hash IS NULL OR octet_length(entry_hash) = 32");

                            t.HasCheckConstraint("ck_audit_logs_metadata_json_shape", "metadata_json IS NULL OR jsonb_typeof(metadata_json) IN ('object','array')");

                            t.HasCheckConstraint("ck_audit_logs_new_values_json_shape", "new_values_json IS NULL OR jsonb_typeof(new_values_json) IN ('object','array')");

                            t.HasCheckConstraint("ck_audit_logs_old_values_json_shape", "old_values_json IS NULL OR jsonb_typeof(old_values_json) IN ('object','array')");

                            t.HasCheckConstraint("ck_audit_logs_outcome", "outcome IN ('SUCCESS','FAILURE','DENIED')");

                            t.HasCheckConstraint("ck_audit_logs_previous_hash_length", "previous_entry_hash IS NULL OR octet_length(previous_entry_hash) = 32");
                        });
                });

            modelBuilder.Entity("ItAssetManagement.Domain.Entities.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentDepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_department_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_departments_created_by_user_id");

                    b.HasIndex("ParentDepartmentId")
                        .HasDatabaseName("ix_departments_parent");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_departments_updated_by_user_id");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("ix_departments_active_name");

                    b.ToTable("departments", "public", t =>
                        {
                            t.HasCheckConstraint("ck_departments_parent_not_self", "parent_department_id <> id");

                            t.HasCheckConstraint("ck_departments_row_version_length", "octet_length(row_version) = 16");
                        });
                });

            modelBuilder.Entity("ItAssetManagement.Domain.Entities.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Module", "IsActive")
                        .HasDatabaseName("ix_permissions_module_active");

                    b.ToTable("permissions", "public", t =>
                        {
                            t.HasCheckConstraint("ck_permissions_row_version_length", "octet_length(row_version) = 16");
                        });
                });

            modelBuilder.Entity("ItAssetManagement.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("ix_roles_active_name");

                    b.ToTable("roles", "public", t =>
                        {
                            t.HasCheckConstraint("ck_roles_row_version_length", "octet_length(row_version) = 16");
                        });
                });

            modelBuilder.Entity("ItAssetManagement.Domain.Entities.RolePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("GrantedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at_utc")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<long?>("GrantedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("granted_by_user_id");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("permission_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_permissions");

                    b.HasIndex("GrantedByUserId")
                        .HasDatabaseName("ix_role_permissions_granted_by_user_id");

                    b.HasIndex("PermissionId", "RoleId")
                        .HasDatabaseName("ix_role_permissions_permission");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("uq_role_permissions_role_permission");

                    b.ToTable("role_permissions", "public");
                });

            modelBuilder.Entity("ItAssetManagement.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AdminLockedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("admin_locked_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_code");

                    b.Property<int>("FailedLoginCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdminLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin_locked");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end_utc");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<int>("TokenVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("token_version");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_users_created_by_user_id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("uq_users_normalized_email");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("uq_users_normalized_username");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_users_updated_by_user_id");

                    b.HasIndex("DepartmentId", "IsActive")
                        .HasDatabaseName("ix_users_department_active");

                    b.ToTable("users", "public", t =>
                        {
                            t.HasCheckConstraint("ck_users_admin_lock_time", "(NOT is_admin_locked AND admin_locked_at_utc IS NULL) OR (is_admin_locked AND admin_locked_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_users_failed_login_nonnegative", "failed_login_count >= 0");

                            t.HasCheckConstraint("ck_users_row_version_length", "octet_length(row_version) = 16");

                            t.HasCheckConstraint("ck_users_token_version_nonnegative", "token_version >= 0");
                        });
                });

            modelBuilder.Entity("ItAssetManagement.Domain.Entities.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AssignedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<long?>("AssignedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("AssignedByUserId")
                        .HasDatabaseName("ix_user_roles_assigned_by_user_id");

                    b.HasIndex("RoleId", "UserId")
                        .HasDatabaseName("ix_user_roles_role");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("uq_user_roles_user_role");

                    b.ToTable("user_roles", "public");
                });

            modelBuilder.Entity("ItAssetManagement.Domain.Entities.Asset", b =>
                {
                    b.HasOne("ItAssetManagement.Domain.Entities.AssetType", null)
                        .WithMany()
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_assets_asset_type_id");

                    b.HasOne("ItAssetManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_assets_created_by_user_id");

                    b.HasOne("ItAssetManagement.Domain.Entities.Department", null)
                        .WithMany()
                        .HasForeignKey("OwningDepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_assets_owning_department_id");

                    b.HasOne("ItAssetManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_assets_updated_by_user_id");
                });

            modelBuilder.Entity("ItAssetManagement.Domain.Entities.AssetStatusHistory", b =>
                {
                    b.HasOne("ItAssetManagement.Domain.Entities.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_asset_status_histories_asset_id");

                    b.HasOne("ItAssetManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_asset_status_histories_changed_by_user_id");
                });

            modelBuilder.Entity("ItAssetManagement.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("ItAssetManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_audit_logs_actor_user_id");
                });

            modelBuilder.Entity("ItAssetManagement.Domain.Entities.Department", b =>
                {
                    b.HasOne("ItAssetManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_departments_created_by_user_id");

                    b.HasOne("ItAssetManagement.Domain.Entities.Department", null)
                        .WithMany()
                        .HasForeignKey("ParentDepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_departments_parent_department_id");

                    b.HasOne("ItAssetManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_departments_updated_by_user_id");
                });

            modelBuilder.Entity("ItAssetManagement.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("ItAssetManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_role_permissions_granted_by_user_id");

                    b.HasOne("ItAssetManagement.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permission_id");

                    b.HasOne("ItAssetManagement.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_role_id");
                });

            modelBuilder.Entity("ItAssetManagement.Domain.Entities.User", b =>
                {
                    b.HasOne("ItAssetManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_users_created_by_user_id");

                    b.HasOne("ItAssetManagement.Domain.Entities.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_users_department_id");

                    b.HasOne("ItAssetManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_users_updated_by_user_id");
                });

            modelBuilder.Entity("ItAssetManagement.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("ItAssetManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_user_roles_assigned_by_user_id");

                    b.HasOne("ItAssetManagement.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_role_id");

                    b.HasOne("ItAssetManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
