START TRANSACTION;
CREATE TABLE public.asset_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    asset_id bigint NOT NULL,
    assigned_user_id bigint,
    assigned_department_id bigint,
    assigned_at_utc timestamp with time zone NOT NULL DEFAULT (clock_timestamp()),
    expected_return_at_utc timestamp with time zone,
    returned_at_utc timestamp with time zone,
    assigned_by_user_id bigint NOT NULL,
    returned_by_user_id bigint,
    assignment_note character varying(1000),
    return_note character varying(1000),
    is_archived boolean NOT NULL DEFAULT FALSE,
    created_at_utc timestamp with time zone NOT NULL DEFAULT (clock_timestamp()),
    row_version bytea NOT NULL,
    CONSTRAINT pk_asset_assignments PRIMARY KEY (id),
    CONSTRAINT ck_asset_assignments_closed_before_archive CHECK (NOT is_archived OR returned_at_utc IS NOT NULL),
    CONSTRAINT ck_asset_assignments_expected_after_assigned CHECK (expected_return_at_utc IS NULL OR expected_return_at_utc >= assigned_at_utc),
    CONSTRAINT ck_asset_assignments_returned_actor CHECK (returned_by_user_id IS NULL OR returned_at_utc IS NOT NULL),
    CONSTRAINT ck_asset_assignments_returned_after_assigned CHECK (returned_at_utc IS NULL OR returned_at_utc >= assigned_at_utc),
    CONSTRAINT ck_asset_assignments_row_version_length CHECK (octet_length(row_version) = 16),
    CONSTRAINT ck_asset_assignments_target_xor CHECK ((assigned_user_id IS NOT NULL AND assigned_department_id IS NULL) OR (assigned_user_id IS NULL AND assigned_department_id IS NOT NULL)),
    CONSTRAINT fk_asset_assignments_asset_id FOREIGN KEY (asset_id) REFERENCES public.assets (id),
    CONSTRAINT fk_asset_assignments_assigned_by_user_id FOREIGN KEY (assigned_by_user_id) REFERENCES public.users (id),
    CONSTRAINT fk_asset_assignments_assigned_department_id FOREIGN KEY (assigned_department_id) REFERENCES public.departments (id),
    CONSTRAINT fk_asset_assignments_assigned_user_id FOREIGN KEY (assigned_user_id) REFERENCES public.users (id),
    CONSTRAINT fk_asset_assignments_returned_by_user_id FOREIGN KEY (returned_by_user_id) REFERENCES public.users (id)
);

CREATE TABLE public.maintenance_tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    ticket_code character varying(50) NOT NULL,
    asset_id bigint NOT NULL,
    title character varying(250) NOT NULL,
    description character varying(4000) NOT NULL,
    priority character varying(20) NOT NULL DEFAULT 'MEDIUM',
    status character varying(30) NOT NULL DEFAULT 'PENDING',
    requested_by_user_id bigint NOT NULL,
    assigned_to_user_id bigint,
    opened_at_utc timestamp with time zone NOT NULL DEFAULT (clock_timestamp()),
    due_at_utc timestamp with time zone,
    started_at_utc timestamp with time zone,
    resolved_at_utc timestamp with time zone,
    resolution character varying(4000),
    estimated_cost numeric(18,2),
    actual_cost numeric(18,2),
    is_archived boolean NOT NULL DEFAULT FALSE,
    created_at_utc timestamp with time zone NOT NULL DEFAULT (clock_timestamp()),
    updated_at_utc timestamp with time zone,
    row_version bytea NOT NULL,
    CONSTRAINT pk_maintenance_tickets PRIMARY KEY (id),
    CONSTRAINT ck_maintenance_tickets_actual_cost_nonnegative CHECK (actual_cost IS NULL OR (actual_cost >= 0 AND actual_cost <> 'NaN'::numeric)),
    CONSTRAINT ck_maintenance_tickets_archive_terminal CHECK (NOT is_archived OR status IN ('RESOLVED','FAILED','CANCELLED')),
    CONSTRAINT ck_maintenance_tickets_due_after_opened CHECK (due_at_utc IS NULL OR due_at_utc >= opened_at_utc),
    CONSTRAINT ck_maintenance_tickets_estimated_cost_nonnegative CHECK (estimated_cost IS NULL OR (estimated_cost >= 0 AND estimated_cost <> 'NaN'::numeric)),
    CONSTRAINT ck_maintenance_tickets_in_progress_requires_assignee CHECK (status NOT IN ('IN_PROGRESS','RESOLVED','FAILED') OR (assigned_to_user_id IS NOT NULL AND started_at_utc IS NOT NULL)),
    CONSTRAINT ck_maintenance_tickets_priority CHECK (priority IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    CONSTRAINT ck_maintenance_tickets_resolved_after_started CHECK (resolved_at_utc IS NULL OR resolved_at_utc >= COALESCE(started_at_utc, opened_at_utc)),
    CONSTRAINT ck_maintenance_tickets_resolved_requires_resolution CHECK (status NOT IN ('RESOLVED','FAILED') OR (resolution IS NOT NULL AND resolved_at_utc IS NOT NULL)),
    CONSTRAINT ck_maintenance_tickets_row_version_length CHECK (octet_length(row_version) = 16),
    CONSTRAINT ck_maintenance_tickets_started_after_opened CHECK (started_at_utc IS NULL OR started_at_utc >= opened_at_utc),
    CONSTRAINT ck_maintenance_tickets_status CHECK (status IN ('PENDING','IN_PROGRESS','RESOLVED','FAILED','CANCELLED')),
    CONSTRAINT fk_maintenance_tickets_asset_id FOREIGN KEY (asset_id) REFERENCES public.assets (id),
    CONSTRAINT fk_maintenance_tickets_assigned_to_user_id FOREIGN KEY (assigned_to_user_id) REFERENCES public.users (id),
    CONSTRAINT fk_maintenance_tickets_requested_by_user_id FOREIGN KEY (requested_by_user_id) REFERENCES public.users (id)
);

CREATE INDEX ix_asset_assignments_asset_history ON public.asset_assignments (asset_id, assigned_at_utc DESC);

CREATE INDEX ix_asset_assignments_assigned_by_user_id ON public.asset_assignments (assigned_by_user_id);

CREATE INDEX ix_asset_assignments_department_active ON public.asset_assignments (assigned_department_id, returned_at_utc) WHERE assigned_department_id IS NOT NULL;

CREATE INDEX ix_asset_assignments_returned_by_user_id ON public.asset_assignments (returned_by_user_id);

CREATE INDEX ix_asset_assignments_user_active ON public.asset_assignments (assigned_user_id, returned_at_utc) WHERE assigned_user_id IS NOT NULL;

CREATE UNIQUE INDEX uq_asset_assignments_one_active ON public.asset_assignments (asset_id) WHERE returned_at_utc IS NULL AND NOT is_archived;

CREATE INDEX ix_maintenance_tickets_asset_status ON public.maintenance_tickets (asset_id, status);

CREATE INDEX ix_maintenance_tickets_assignee_status ON public.maintenance_tickets (assigned_to_user_id, status, due_at_utc);

CREATE INDEX ix_maintenance_tickets_open ON public.maintenance_tickets (status, opened_at_utc DESC);

CREATE INDEX ix_maintenance_tickets_requested_by_user_id ON public.maintenance_tickets (requested_by_user_id);

CREATE UNIQUE INDEX uq_maintenance_one_in_progress ON public.maintenance_tickets (asset_id) WHERE status = 'IN_PROGRESS' AND NOT is_archived;

CREATE UNIQUE INDEX uq_maintenance_tickets_code ON public.maintenance_tickets (lower(ticket_code));

INSERT INTO public.ef_migrations_history ("MigrationId", "ProductVersion")
VALUES ('20261008080630_AddAssignmentMaintenance', '10.0.11');

COMMIT;
