START TRANSACTION;
-- Prepared operator script. DO NOT run on neondb until backup/recovery/rollout approval.
-- psql must use ON_ERROR_STOP=1; secrets through a private environment/passfile only.
SET LOCAL lock_timeout = '3s';
SET LOCAL statement_timeout = '60s';
DO $preflight$
BEGIN
    IF current_database() <> 'neondb' AND current_database() !~ '^it_asset_management_full_schema_verify_[a-z0-9_]{1,24}$' THEN
        RAISE EXCEPTION 'UNAPPROVED_DATABASE_TARGET';
    END IF;
    IF NOT pg_try_advisory_xact_lock(837112, 100) THEN
        RAISE EXCEPTION 'DATABASE_CHANGE_LOCK_BUSY';
    END IF;
    IF (SELECT array_agg(tablename::text ORDER BY tablename) FROM pg_tables WHERE schemaname='public') <>
       ARRAY['asset_assignments','asset_status_histories','asset_types','assets','audit_logs','departments','ef_migrations_history','maintenance_tickets','permissions','role_permissions','roles','user_roles','users'] THEN
        RAISE EXCEPTION 'EXPECTED_EXACT_12_TABLE_BASELINE';
    END IF;
    IF (SELECT array_agg("MigrationId" ORDER BY "MigrationId") FROM public.ef_migrations_history) <>
       ARRAY['20261002151601_InitialM1','20261008080630_AddAssignmentMaintenance']::varchar[] THEN
        RAISE EXCEPTION 'MIGRATION_HISTORY_MISMATCH';
    END IF;
    IF (SELECT count(*) FROM pg_constraint WHERE connamespace='public'::regnamespace AND contype='f' AND confdeltype='a') <> 27 OR
       EXISTS(SELECT 1 FROM pg_constraint WHERE connamespace='public'::regnamespace AND NOT convalidated) THEN
        RAISE EXCEPTION 'BASELINE_FOREIGN_KEYS_MISMATCH';
    END IF;
END;
$preflight$;
CREATE TABLE public.maintenance_histories (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    maintenance_ticket_id bigint NOT NULL,
    event_type character varying(30) NOT NULL,
    from_status character varying(30),
    to_status character varying(30),
    from_assigned_to_user_id bigint,
    to_assigned_to_user_id bigint,
    comment character varying(4000),
    cost numeric(18,2),
    performed_by_user_id bigint,
    performed_at_utc timestamp with time zone NOT NULL DEFAULT (clock_timestamp()),
    correlation_id uuid NOT NULL,
    CONSTRAINT pk_maintenance_histories PRIMARY KEY (id),
    CONSTRAINT ck_maintenance_histories_cost_nonnegative CHECK (cost IS NULL OR (cost >= 0 AND cost <> 'NaN'::numeric)),
    CONSTRAINT ck_maintenance_histories_event_type CHECK (event_type IN ('CREATED','STATUS_CHANGED','ASSIGNED','COMMENTED','COST_UPDATED','RESOLVED','FAILED','CANCELLED')),
    CONSTRAINT ck_maintenance_histories_from_status CHECK (from_status IN ('PENDING','IN_PROGRESS','RESOLVED','FAILED','CANCELLED')),
    CONSTRAINT ck_maintenance_histories_to_status CHECK (to_status IN ('PENDING','IN_PROGRESS','RESOLVED','FAILED','CANCELLED')),
    CONSTRAINT fk_maintenance_histories_from_assigned_to_user_id FOREIGN KEY (from_assigned_to_user_id) REFERENCES public.users (id),
    CONSTRAINT fk_maintenance_histories_maintenance_ticket_id FOREIGN KEY (maintenance_ticket_id) REFERENCES public.maintenance_tickets (id),
    CONSTRAINT fk_maintenance_histories_performed_by_user_id FOREIGN KEY (performed_by_user_id) REFERENCES public.users (id),
    CONSTRAINT fk_maintenance_histories_to_assigned_to_user_id FOREIGN KEY (to_assigned_to_user_id) REFERENCES public.users (id)
);

CREATE TABLE public.replacement_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code character varying(100) NOT NULL,
    version integer NOT NULL DEFAULT 1,
    name character varying(250) NOT NULL,
    asset_type_id bigint,
    minimum_age_months integer,
    maximum_maintenance_cost_ratio numeric(5,4),
    minimum_maintenance_count integer,
    require_warranty_expired boolean NOT NULL DEFAULT FALSE,
    minimum_failure_count integer,
    estimated_unit_cost numeric(18,2),
    priority integer NOT NULL DEFAULT 100,
    effective_from_utc timestamp with time zone NOT NULL DEFAULT (clock_timestamp()),
    effective_to_utc timestamp with time zone,
    is_active boolean NOT NULL DEFAULT TRUE,
    description character varying(2000),
    created_at_utc timestamp with time zone NOT NULL DEFAULT (clock_timestamp()),
    updated_at_utc timestamp with time zone,
    row_version bytea NOT NULL,
    CONSTRAINT pk_replacement_rules PRIMARY KEY (id),
    CONSTRAINT ck_replacement_rules_at_least_one_condition CHECK (minimum_age_months IS NOT NULL OR maximum_maintenance_cost_ratio IS NOT NULL OR minimum_maintenance_count IS NOT NULL OR require_warranty_expired OR minimum_failure_count IS NOT NULL),
    CONSTRAINT ck_replacement_rules_effective_period CHECK (effective_to_utc IS NULL OR effective_to_utc > effective_from_utc),
    CONSTRAINT ck_replacement_rules_estimated_unit_cost_nonnegative CHECK (estimated_unit_cost IS NULL OR (estimated_unit_cost >= 0 AND estimated_unit_cost <> 'NaN'::numeric)),
    CONSTRAINT ck_replacement_rules_minimum_age_months_positive CHECK (minimum_age_months IS NULL OR minimum_age_months > 0),
    CONSTRAINT ck_replacement_rules_minimum_failure_count_positive CHECK (minimum_failure_count IS NULL OR minimum_failure_count > 0),
    CONSTRAINT ck_replacement_rules_minimum_maintenance_count_positive CHECK (minimum_maintenance_count IS NULL OR minimum_maintenance_count > 0),
    CONSTRAINT ck_replacement_rules_priority_nonnegative CHECK (priority >= 0),
    CONSTRAINT ck_replacement_rules_ratio CHECK (maximum_maintenance_cost_ratio IS NULL OR maximum_maintenance_cost_ratio BETWEEN 0 AND 1),
    CONSTRAINT ck_replacement_rules_row_version_length CHECK (octet_length(row_version) = 16),
    CONSTRAINT ck_replacement_rules_version_positive CHECK (version > 0),
    CONSTRAINT fk_replacement_rules_asset_type_id FOREIGN KEY (asset_type_id) REFERENCES public.asset_types (id)
);

CREATE TABLE public.softwares (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    code character varying(50) NOT NULL,
    name character varying(250) NOT NULL,
    publisher character varying(250),
    version character varying(100),
    description character varying(2000),
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at_utc timestamp with time zone NOT NULL DEFAULT (clock_timestamp()),
    updated_at_utc timestamp with time zone,
    row_version bytea NOT NULL,
    CONSTRAINT pk_softwares PRIMARY KEY (id),
    CONSTRAINT ck_softwares_row_version_length CHECK (octet_length(row_version) = 16)
);

CREATE TABLE public.replacement_recommendations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    asset_id bigint NOT NULL,
    replacement_rule_id bigint NOT NULL,
    disposition character varying(30) NOT NULL DEFAULT 'ACTIVE',
    is_current boolean NOT NULL DEFAULT TRUE,
    priority character varying(20) NOT NULL,
    score numeric(9,4),
    reason character varying(2000) NOT NULL,
    estimated_replacement_cost numeric(18,2),
    planned_replacement_year smallint,
    evaluation_snapshot_json jsonb NOT NULL,
    recommended_at_utc timestamp with time zone NOT NULL DEFAULT (clock_timestamp()),
    disposition_at_utc timestamp with time zone,
    disposition_by_user_id bigint,
    disposition_note character varying(2000),
    is_archived boolean NOT NULL DEFAULT FALSE,
    created_at_utc timestamp with time zone NOT NULL DEFAULT (clock_timestamp()),
    updated_at_utc timestamp with time zone,
    row_version bytea NOT NULL,
    CONSTRAINT pk_replacement_recommendations PRIMARY KEY (id),
    CONSTRAINT ck_replacement_recommendations_archive_disposition CHECK (NOT is_archived OR disposition <> 'ACTIVE'),
    CONSTRAINT ck_replacement_recommendations_current_disposition CHECK (NOT is_current OR (disposition IN ('ACTIVE','PLANNED') AND NOT is_archived)),
    CONSTRAINT ck_replacement_recommendations_disposition CHECK (disposition IN ('ACTIVE','PLANNED','DISMISSED','SUPERSEDED')),
    CONSTRAINT ck_replacement_recommendations_disposition_actor CHECK (disposition_by_user_id IS NULL OR disposition_at_utc IS NOT NULL),
    CONSTRAINT ck_replacement_recommendations_disposition_evidence CHECK ((disposition = 'ACTIVE' AND disposition_at_utc IS NULL) OR (disposition IN ('PLANNED','DISMISSED') AND disposition_at_utc IS NOT NULL AND disposition_by_user_id IS NOT NULL) OR (disposition = 'SUPERSEDED' AND disposition_at_utc IS NOT NULL)),
    CONSTRAINT ck_replacement_recommendations_disposition_time CHECK (disposition_at_utc IS NULL OR disposition_at_utc >= recommended_at_utc),
    CONSTRAINT "ck_replacement_recommendations_estimated_replacement_cost_nonn~" CHECK (estimated_replacement_cost IS NULL OR (estimated_replacement_cost >= 0 AND estimated_replacement_cost <> 'NaN'::numeric)),
    CONSTRAINT ck_replacement_recommendations_planned_year CHECK (planned_replacement_year IS NULL OR planned_replacement_year BETWEEN 2000 AND 2100),
    CONSTRAINT ck_replacement_recommendations_priority CHECK (priority IN ('LOW','MEDIUM','HIGH','CRITICAL')),
    CONSTRAINT ck_replacement_recommendations_row_version_length CHECK (octet_length(row_version) = 16),
    CONSTRAINT ck_replacement_recommendations_score_nonnegative CHECK (score IS NULL OR (score >= 0 AND score <> 'NaN'::numeric)),
    CONSTRAINT ck_replacement_recommendations_snapshot_shape CHECK (jsonb_typeof(evaluation_snapshot_json) IN ('object','array')),
    CONSTRAINT fk_replacement_recommendations_asset_id FOREIGN KEY (asset_id) REFERENCES public.assets (id),
    CONSTRAINT fk_replacement_recommendations_disposition_by_user_id FOREIGN KEY (disposition_by_user_id) REFERENCES public.users (id),
    CONSTRAINT fk_replacement_recommendations_replacement_rule_id FOREIGN KEY (replacement_rule_id) REFERENCES public.replacement_rules (id)
);

CREATE TABLE public.software_licenses (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    software_id bigint NOT NULL,
    license_code character varying(100) NOT NULL,
    vendor character varying(250),
    license_type character varying(30) NOT NULL,
    total_quantity integer NOT NULL,
    license_key_ciphertext bytea,
    license_key_last4 character varying(4),
    key_version character varying(50),
    purchased_at_utc timestamp with time zone,
    starts_at_utc timestamp with time zone,
    expires_at_utc timestamp with time zone,
    purchase_cost numeric(18,2),
    notes character varying(2000),
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at_utc timestamp with time zone NOT NULL DEFAULT (clock_timestamp()),
    updated_at_utc timestamp with time zone,
    row_version bytea NOT NULL,
    CONSTRAINT pk_software_licenses PRIMARY KEY (id),
    CONSTRAINT ck_software_licenses_expiry CHECK (expires_at_utc IS NULL OR starts_at_utc IS NULL OR expires_at_utc > starts_at_utc),
    CONSTRAINT ck_software_licenses_key_last4 CHECK (license_key_last4 IS NULL OR char_length(license_key_last4) = 4),
    CONSTRAINT ck_software_licenses_key_tuple CHECK ((license_key_ciphertext IS NULL AND license_key_last4 IS NULL AND key_version IS NULL) OR (license_key_ciphertext IS NOT NULL AND license_key_last4 IS NOT NULL AND key_version IS NOT NULL)),
    CONSTRAINT ck_software_licenses_purchase_cost_nonnegative CHECK (purchase_cost IS NULL OR (purchase_cost >= 0 AND purchase_cost <> 'NaN'::numeric)),
    CONSTRAINT ck_software_licenses_quantity_positive CHECK (total_quantity > 0),
    CONSTRAINT ck_software_licenses_row_version_length CHECK (octet_length(row_version) = 16),
    CONSTRAINT ck_software_licenses_type CHECK (license_type IN ('PER_USER','PER_DEVICE','VOLUME','SUBSCRIPTION','OTHER')),
    CONSTRAINT fk_software_licenses_software_id FOREIGN KEY (software_id) REFERENCES public.softwares (id)
);

CREATE TABLE public.license_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    software_license_id bigint NOT NULL,
    assigned_user_id bigint,
    assigned_asset_id bigint,
    assigned_at_utc timestamp with time zone NOT NULL DEFAULT (clock_timestamp()),
    revoked_at_utc timestamp with time zone,
    assigned_by_user_id bigint NOT NULL,
    revoked_by_user_id bigint,
    notes character varying(1000),
    is_archived boolean NOT NULL DEFAULT FALSE,
    created_at_utc timestamp with time zone NOT NULL DEFAULT (clock_timestamp()),
    row_version bytea NOT NULL,
    CONSTRAINT pk_license_assignments PRIMARY KEY (id),
    CONSTRAINT ck_license_assignments_closed_before_archive CHECK (NOT is_archived OR revoked_at_utc IS NOT NULL),
    CONSTRAINT ck_license_assignments_revoked_actor CHECK (revoked_by_user_id IS NULL OR revoked_at_utc IS NOT NULL),
    CONSTRAINT ck_license_assignments_revoked_after_assigned CHECK (revoked_at_utc IS NULL OR revoked_at_utc >= assigned_at_utc),
    CONSTRAINT ck_license_assignments_row_version_length CHECK (octet_length(row_version) = 16),
    CONSTRAINT ck_license_assignments_target_xor CHECK ((assigned_user_id IS NOT NULL AND assigned_asset_id IS NULL) OR (assigned_user_id IS NULL AND assigned_asset_id IS NOT NULL)),
    CONSTRAINT fk_license_assignments_assigned_asset_id FOREIGN KEY (assigned_asset_id) REFERENCES public.assets (id),
    CONSTRAINT fk_license_assignments_assigned_by_user_id FOREIGN KEY (assigned_by_user_id) REFERENCES public.users (id),
    CONSTRAINT fk_license_assignments_assigned_user_id FOREIGN KEY (assigned_user_id) REFERENCES public.users (id),
    CONSTRAINT fk_license_assignments_revoked_by_user_id FOREIGN KEY (revoked_by_user_id) REFERENCES public.users (id),
    CONSTRAINT fk_license_assignments_software_license_id FOREIGN KEY (software_license_id) REFERENCES public.software_licenses (id)
);

CREATE INDEX ix_license_assignments_asset_history ON public.license_assignments (assigned_asset_id, assigned_at_utc DESC, id DESC) WHERE assigned_asset_id IS NOT NULL;

CREATE INDEX ix_license_assignments_assigned_by_user_id ON public.license_assignments (assigned_by_user_id);

CREATE INDEX ix_license_assignments_license_active ON public.license_assignments (software_license_id, revoked_at_utc);

CREATE INDEX ix_license_assignments_revoked_by_user_id ON public.license_assignments (revoked_by_user_id);

CREATE INDEX ix_license_assignments_user_history ON public.license_assignments (assigned_user_id, assigned_at_utc DESC, id DESC) WHERE assigned_user_id IS NOT NULL;

CREATE UNIQUE INDEX uq_license_assignments_active_asset ON public.license_assignments (software_license_id, assigned_asset_id) WHERE revoked_at_utc IS NULL AND NOT is_archived AND assigned_asset_id IS NOT NULL;

CREATE UNIQUE INDEX uq_license_assignments_active_user ON public.license_assignments (software_license_id, assigned_user_id) WHERE revoked_at_utc IS NULL AND NOT is_archived AND assigned_user_id IS NOT NULL;

CREATE INDEX ix_maintenance_histories_correlation ON public.maintenance_histories (correlation_id);

CREATE INDEX ix_maintenance_histories_from_assigned_to_user_id ON public.maintenance_histories (from_assigned_to_user_id);

CREATE INDEX ix_maintenance_histories_performed_by_user_id ON public.maintenance_histories (performed_by_user_id);

CREATE INDEX ix_maintenance_histories_ticket_time ON public.maintenance_histories (maintenance_ticket_id, performed_at_utc, id);

CREATE INDEX ix_maintenance_histories_to_assigned_to_user_id ON public.maintenance_histories (to_assigned_to_user_id);

CREATE INDEX ix_replacement_recommendations_asset ON public.replacement_recommendations (asset_id, recommended_at_utc DESC);

CREATE INDEX ix_replacement_recommendations_budget ON public.replacement_recommendations (planned_replacement_year, is_current, asset_id) INCLUDE (estimated_replacement_cost);

CREATE INDEX ix_replacement_recommendations_disposition_by_user_id ON public.replacement_recommendations (disposition_by_user_id);

CREATE INDEX ix_replacement_recommendations_disposition_time ON public.replacement_recommendations (disposition, priority, recommended_at_utc DESC);

CREATE INDEX ix_replacement_recommendations_replacement_rule_id ON public.replacement_recommendations (replacement_rule_id);

CREATE UNIQUE INDEX uq_replacement_recommendations_current_asset ON public.replacement_recommendations (asset_id) WHERE is_current = true;

CREATE INDEX ix_replacement_rules_asset_type_id ON public.replacement_rules (asset_type_id);

CREATE INDEX ix_replacement_rules_evaluation ON public.replacement_rules (is_active, asset_type_id, priority, effective_from_utc, effective_to_utc);

CREATE INDEX ix_software_licenses_expiry ON public.software_licenses (expires_at_utc) WHERE expires_at_utc IS NOT NULL AND is_active = true;

CREATE INDEX ix_software_licenses_software_active ON public.software_licenses (software_id, is_active);

CREATE INDEX ix_softwares_active ON public.softwares (is_active, name);

CREATE INDEX ix_softwares_name_publisher ON public.softwares (name, publisher);

CREATE UNIQUE INDEX uq_softwares_code ON public.softwares (lower(code));
CREATE UNIQUE INDEX uq_software_licenses_code ON public.software_licenses (lower(license_code));
CREATE UNIQUE INDEX uq_replacement_rules_code_version ON public.replacement_rules (lower(code), version);
CREATE UNIQUE INDEX uq_replacement_rules_one_current ON public.replacement_rules (lower(code))
  WHERE is_active = true AND effective_to_utc IS NULL;
CREATE TRIGGER maintenance_histories_append_only BEFORE UPDATE OR DELETE OR TRUNCATE
  ON public.maintenance_histories FOR EACH STATEMENT EXECUTE FUNCTION public.reject_history_mutation();

INSERT INTO public.ef_migrations_history ("MigrationId", "ProductVersion")
VALUES ('20261009172549_CompleteBaselineV1', '10.0.11');

COMMIT;
